bookmarks/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth.views import LoginView 
from .views import *
from django.views.generic import TemplateView
from bookmarks.feeds import *
from django.urls import path

urlpatterns = [

     path('latest/feed/', RecentBookmarks()),

    # Browsing
    url(r'^$', main_page, name="main_page"),
    url(r'^user/(\w+)/$', user_page, name="users_page"),
    url(r'^popular/$', popular_page, name="popular_page"),
    # Session management
    url(r'^login/$',  LoginView.as_view(), name="login_page" ),
    url(r'^logout/$', logout_page, name="logout_page"),
    url(r'^register/$', register_page, name="register_page"),
    url(r'^register/success/$', TemplateView.as_view( template_name =  'registration/register_success.html' ), name="registration_success"),
    # Account management
    url(r'^save/$', bookmark_save_page, name="bookmark_save"),
    url(r'^tag/([^\s]+)/$', tag_page, name="tag_page"),
    url(r'^tag/$', tag_cloud_page, name="tag_cloud_page"),
    url(r'^search/$', search_page, name="search_page"),

    # Ajax
    url(r'^ajax/tag/autocomplete/$', ajax_tag_autocomplete, name="ajax_tag_autocomplete_page"),

    url(r'^vote/$', bookmark_vote_page, name="bookmark_vote_page"),
    url(r'^bookmark/(\d+)/$', bookmark_page, name="bookmark_page"),


    # Friends
    url(r'^friends/(\w+)/$', friends_page, name="friends_page"),

    url(r'^friend/add/$', friend_add, name="friend_add"),
    url(r'^friend/invite/$', friend_invite, name="friend_invite_page"),
    url(r'^friend/accept/(\w+)/$', friend_accept),
]

django_bookmarks/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('bookmarks.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]





if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bookmarks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.template.loader import get_template
from django.template import Context
from django.conf import settings


# Create your models here.


class Link(models.Model):
    url = models.URLField(unique=True)


    def __str__(self):
        return self.url

class Bookmark(models.Model):
    title = models.CharField(max_length=200, verbose_name="Title of the Bookmark", blank=False, null=False, default="")
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    link = models.ForeignKey(Link, on_delete=models.CASCADE)


    def __str__(self):
        return self.title

    
    def get_absolute_url(self):
        return self.link.url



class Tag(models.Model):
    name = models.CharField(max_length=64, unique=True)
    bookmarks = models.ManyToManyField(Bookmark)


    def __str__(self):
        return self.name

class SharedBookmark(models.Model):
    bookmark = models.ForeignKey(Bookmark, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    votes = models.IntegerField(default=1)
    users_voted = models.ManyToManyField(get_user_model() )

    def __str__(self):
        return  self.bookmark.title


class Friendship(models.Model):
    from_friend = models.ForeignKey(
    get_user_model(), related_name='friend_set',
    on_delete=models.CASCADE
    )
    to_friend = models.ForeignKey(
    get_user_model(), related_name='to_friend_set',
    on_delete=models.CASCADE
    )


    def __str__(self):
        return '%s, %s' % (
        self.from_friend.username,
        self.to_friend.username
        )


    class Meta:
        unique_together = (('to_friend', 'from_friend'), )


class Invitation(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    code = models.CharField(max_length=20)
    sender = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    
    def __str__(self):
        return '%s, %s' % (self.sender.username, self.email)
    
    def send(self):
        subject = 'Invitation to join Django Bookmarks'
        link = '%s/friend/accept/%s/' % (
        settings.SITE_REDIRECT_ORIGINAL,
        self.code
        )
        template = get_template('Email/invitation_email.txt')
        context = {
        'name': self.name,
        'link': link,
        'sender': self.sender.username,
        }
        message = template.render(context)
        send_mail(
        subject, message,
        settings.DEFAULT_FROM_EMAIL, [self.email]
        )

bookmarks/forms.py
from django import forms
import re
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import gettext_lazy as _


class RegistrationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=30)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(
    label='Password',
    widget=forms.PasswordInput()
    )
    password2 = forms.CharField(
    label='Password (Again)',
    widget=forms.PasswordInput()
    )

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
                return password2
        raise forms.ValidationError('Passwords do not match.')

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError('Username can only contain alphanumeric characters and the underscore.')
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError('Username is already taken.')


class BookmarkSaveForm(forms.Form):
    url = forms.URLField(
    label='URL',
    widget=forms.TextInput(attrs={'size': 64})
    )
    title = forms.CharField(
    label='Title',
    widget=forms.TextInput(attrs={'size': 64})
    )
    tags = forms.CharField(
    label='Tags',
    required=False,
    widget=forms.TextInput(attrs={'size': 64})
    )
    share = forms.BooleanField(
    label='Share on the main page',
    required=False
    )

class SearchForm(forms.Form):
    query = forms.CharField(
    label='Enter a keyword to search for',
    widget=forms.TextInput(attrs={'size': 32})
    )


class FriendInviteForm(forms.Form):
    name = forms.CharField(label=_("Friend's Name"))
    email = forms.EmailField(label=_("Friend's Email"))

bookmarks/views.py
from re import template
import json
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.contrib.auth import logout
from bookmarks.forms import *
from .models import *
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from datetime import datetime, timedelta
import pytz
from django.utils import timezone
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib import messages
from django.utils.translation import gettext as _


# Main Page
def main_page(request):
    shared_bookmarks = SharedBookmark.objects.order_by(
    '-date'
    )[:10]
    template_name = "main_page.html"
    context = {
    'head_title': 'Django Bookmarks',
    'page_title': 'Welcome to Django Bookmarks',
    'page_body': 'Where you can store and share bookmarks!',
    'shared_bookmarks': shared_bookmarks
    }
    return render(request, template_name, context)


# User Detail Page

def user_page(request, username):
    template_name="user_page.html"
    user = get_object_or_404(User, username=username)
    query_set = user.bookmark_set.order_by('-id')
    ITEMS_PER_PAGE = settings.ITEMS_PER_PAGE
    paginator = Paginator(query_set, ITEMS_PER_PAGE)
    is_friend = Friendship.objects.filter(
    from_friend=request.user,
    to_friend=user
    )
    try:
            page = int(request.GET['page'])
    except:
        page = 1
    try:
        bookmarks = paginator.page(page)
    except:
        raise Http404
    context =  {
        'bookmarks': bookmarks,
        'username': username,
        'show_tags': True,
        'show_edit': username == request.user.username,
        'show_paginator': paginator.num_pages > 1,
        'has_prev': bookmarks.has_previous(),
        'has_next': bookmarks.has_next(),
        'page': bookmarks,
        'pages': paginator.num_pages,
        'next_page': page + 1,
        'prev_page': page - 1,
        'is_friend': is_friend
    }
    return render(request, template_name, context)

# Logout Page
def logout_page(request):
    logout(request)
    return HttpResponseRedirect('/')


# Registration Page
def register_page(request):
    template_name= "registration/register.html"
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password1'],
            email=form.cleaned_data['email']
            )
            if 'invitation' in request.session:
                # Retrieve the invitation object.
                invitation = Invitation.objects.get(id=request.session['invitation'])
                # Create friendship from user to sender.
                friendship = Friendship(
                from_friend=user,
                to_friend=invitation.sender
                )
                friendship.save()
                # Create friendship from sender to user.
                friendship = Friendship (
                from_friend=invitation.sender,
                to_friend=user
                )
                friendship.save()
                # Delete the invitation from the database and session.
                invitation.delete()
                del request.session['invitation']
            return HttpResponseRedirect('/register/success/')
    else:
        form = RegistrationForm()
        context ={
            'form': form
        }
        return render(request, template_name, context)



def bookmark_save_page(request):
    ajax = request.GET.get('ajax', None)
    if request.method == 'POST':
        print(request.POST)
        form = BookmarkSaveForm(request.POST)
        if form.is_valid():
            bookmark = _bookmark_save(request, form)
            if ajax:
                context =  {
                'bookmarks': [bookmark],
                'show_edit': True,
                'show_tags': True
                }
                return render(request , 'bookmark_list.html', context)
            else:
                return HttpResponseRedirect(
                '/user/%s/' % request.user.username
                )
        else:
            if ajax:
                return HttpResponse('failure')
    elif  'url' in request.GET:
        url = request.GET['url']
        title = ''
        tags = ''
        try:
            link = Link.objects.get(url=url)
            bookmark = Bookmark.objects.get(link=link, user=request.user)
            title = bookmark.title
            tags = ' '.join(tag.name for tag in bookmark.tag_set.all())
        except:
            pass
        form = BookmarkSaveForm({
        'url': url,
        'title': title,
        'tags': tags
        })
    else:
        form = BookmarkSaveForm()
    context =  {
    'form': form
    }
    if ajax:
        return render(request,
        'bookmark_save_form.html',
        context
        )
    else:
        return render(request,
        'bookmark_save.html',
        context
        )



def tag_page(request, tag_name):
    template_name="tag_page.html"
    tag = get_object_or_404(Tag, name=tag_name)
    bookmarks = tag.bookmarks.order_by('-id')
    context =  {
        'bookmarks': bookmarks,
        'tag_name': tag_name,
        'show_tags': True,
        'show_user': True
    }
    return render(request, template_name, context)


def tag_cloud_page(request):
    template_name="tag_cloud_page.html"
    MAX_WEIGHT = settings.MAX_WEIGHT
    tags = Tag.objects.order_by('name')
    # Calculate tag, min and max counts.
    min_count = max_count = tags[0].bookmarks.count()
    for tag in tags:
        tag.count = tag.bookmarks.count()
        if tag.count < min_count:
            min_count = tag.count
        if max_count < tag.count:
            max_count = tag.count
    # Calculate count range. Avoid dividing by zero.
    range = float(max_count - min_count)
    if range == 0.0:
        range = 1.0
    # Calculate tag weights.
    for tag in tags:
        tag.weight = int(
            MAX_WEIGHT * (tag.count - min_count) / range
        )
    context =  {
        'tags': tags
    }
    return render(request, template_name, context)


def search_page(request):
    template_name="search.html"
    template_name_1="bookmark_list.html"
    form = SearchForm()
    bookmarks = []
    show_results = False
    if 'query' in request.GET:
        show_results = True
        query = request.GET['query'].strip()
        if query:
            keywords = query.split()
            q = Q()
            for keyword in keywords:
                q = q & Q(title__icontains=keyword)
            form = SearchForm({'query' : query})
            bookmarks = Bookmark.objects.filter(q)[:10]
    context =  { 
        'form': form,
        'bookmarks': bookmarks,
        'show_results': show_results,
        'show_tags': True,
        'show_user': True
    }
    if 'ajax' in  request.GET:
        return render(request, template_name_1, context)
    else:
        return render(request, template_name, context)
    
def _bookmark_save(request, form):
    # Create or get link.
    link, dummy =  Link.objects.get_or_create(url=form.cleaned_data['url'])
    # Create or get bookmark.
    bookmark, created = Bookmark.objects.get_or_create(
    user=request.user,
    link=link
    )
    # Update bookmark title.
    bookmark.title = form.cleaned_data['title']
    # If the bookmark is being updated, clear old tag list.
    if not created:
        bookmark.tag_set.clear()
    # Create new tag list.
    tag_names = form.cleaned_data['tags'].split()
    for tag_name in tag_names:
        tag, dummy = Tag.objects.get_or_create(name=tag_name)
        bookmark.tag_set.add(tag)
    # Share on the main page if requested.
    if form.clean_data['share']:
        shared_bookmark, created = SharedBookmark.objects.get_or_create(
        bookmark=bookmark
        )
        if created:
            shared_bookmark.users_voted.add(request.user)
            shared_bookmark.save()
    # Save bookmark to database and return it.
    bookmark.save()
    return bookmark


def ajax_tag_autocomplete(request):
    # if 'term' in  request.GET:
    #     tags = Tag.objects.filter(name__istartswith=request.GET['term'])[:]
    #     print(tags)
    #     return HttpResponse('\n'.join(tag.name for tag in tags))
    # return HttpResponse()
    if request.is_ajax():
        q = request.GET.get('term', '').capitalize()
        tags = Tag.objects.filter(name__istartswith=request.GET['term'])[:]
        results = []
        for tag in tags:
            results.append(tag.name)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)


@login_required
def bookmark_vote_page(request):
    if 'id' in  request.GET:
        try:
            id = request.GET['id']
            shared_bookmark = SharedBookmark.objects.get(id=id)
            user_voted = shared_bookmark.users_voted.filter(
            username=request.user.username
            )
            if not user_voted:
                shared_bookmark.votes += 1
                shared_bookmark.users_voted.add(request.user)
                shared_bookmark.save()
        except ObjectDoesNotExist:
            raise Http404('Bookmark not found.')
    if 'HTTP_REFERER' in request.META:
        return HttpResponseRedirect(request.META['HTTP_REFERER'])
    return HttpResponseRedirect('/')



bookmarks/templates/bookmarks/base.html
{% load static %}

<!DOCTYPE  html >
<html>
<head>
<title>Django Bookmarks |
{% block title %}{% endblock %}</title>
<link rel="stylesheet" href="{% static 'css/style.css' %}"
type="text/css" />
<script type="text/javascript" src="{% static 'js/firebug.js' %}">
</script>
<script  type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script  type="text/javascript" src="{% static 'js/jquery-ui.js' %}"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" /> <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"> </script> <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
<script  type="text/javascript" src="{% static 'js/tag_autocomplete.js' %}"></script>

{% block external %}{% endblock %}
</head>
<body>
    <div id="nav">
        <a href="/">home</a> |
        <a href="/popular/">popular</a> |
        {% if user.is_authenticated %}
        <a href="/save/">submit</a> |
        <a href="/search/">search</a> |
        <a href="/user/{{ user.username }}/">
        {{ user.username }}</a> |
        <a href="/logout/">logout</a>
        {% else %}
        <a href="/login/">login</a> |
        <a href="/register/">register</a>
        {% endif %}
        </div>
<h1>{% block head %}{% endblock %}</h1>
{% if messages %}
<ul class="messages">
{% for message in messages %}
<li>{{ message }}</li>
{% endfor %}
</ul>
{% endif %}
{% block content %}{% endblock %}
<div id="footer">
    Django Bookmarks <br />
    Languages:
    <a href="/i18n/setlang/?language=en">en</a>
    <a href="/i18n/setlang/?language=de">de</a>
</div>
</body>
</html>

bookmarks/templates/bookmarks/bookmark_list.html
{% if bookmarks %}
<ul class="bookmarks">
{% for bookmark in bookmarks %}
<li>
    <a href="{{ bookmark.link.url|escape }}" class="title">
        {{ bookmark.title|escape }}</a>
        {% if show_edit %}
        <a href="/save/?url={{ bookmark.link.url|urlencode }}"
        class="edit">[edit]</a>
        {% endif %}
<br />
{% if show_tags %}
Tags:
{% if bookmark.tag_set.all %}
<ul class="tags">
    {% for tag in bookmark.tag_set.all %}
    <li><a href="/tag/{{ tag.name|urlencode }}/">
        {{ tag.name|escape }}</a></li>
    {% endfor %}
    </ul>
{% else %}
None.
{% endif %}
<br />
{% endif %}
{% if show_user %}
Posted by:
<a href="/user/{{ bookmark.user.username }}/"
class="username">
{{ bookmark.user.username }}</a>
{% endif %}
</li>
{% endfor %}
</ul>
{% if show_paginator %}
<div class="paginator">
{% if has_prev %}
<a href="?page={{ prev_page }}">&laquo; Previous</a>
{% endif %}
{% if has_next %}
<a href="?page={{ next_page }}">Next &raquo;</a>
{% endif %}
(Page {{ page }} of {{ pages }})
</div>
{% endif %}
{% else %}
<p>No bookmarks found.</p>
{% endif %}

bookmarks/templates/bookmarks/bookmark_page.html
{% extends "base.html" %}
{% load comments %}
{% block title %}Bookmark:
{{ shared_bookmark.bookmark.title|escape }}{% endblock %}
{% block head %}
<a href="/vote/?id={{ shared_bookmark.id }}"
class="vote">[+]</a>
<a href="{{ shared_bookmark.bookmark.link.url }}"
class="title">
{{ shared_bookmark.bookmark.title|escape }}</a>
{% endblock %}
{% block content %}
Posted By:
<a href="/user/{{ shared_bookmark.bookmark.user.username }}/"
class="username">
{{ shared_bookmark.bookmark.user.username }}</a> |
<span class="vote-count">Votes: {{ shared_bookmark.votes }}</span>
<h2>Comments</h2>
{% get_comment_count for bookmarks.sharedbookmark shared_bookmark.id as comment_count %}
<p>Number of comments: {{ comment_count }}</p>
{% render_comment_form for bookmarks.sharedbookmark shared_bookmark.id %}

{% get_comment_list for bookmarks.sharedbookmark shared_bookmark.id as comment_list %}
{% for comment in comment_list %}
<div class="comment">
<p><b>{{ comment.user.username }}</b> said:</p>
{{ comment.comment|escape|urlizetrunc:40|linebreaks }}
</div>
{% endfor %}




{% endblock %}

bookmarks/templates/bookmarks/bookmark_save.html
{% extends "base.html" %}
{% block title %}Save Bookmark{% endblock %}
{% block head %}Save Bookmark{% endblock %}
{% block content %}
{% include 'bookmark_save_form.html' %}
{% endblock %}

bookmarks/templates/bookmarks/bookmark_save_form.html

<form id="save-form" method="post" action="/save/">
    {% csrf_token %}
    

    <p><label for="id_url">URL:</label> <input type="text" name="url" size="64" required="" id="id_url"></p>
<p><label for="id_title">Title:</label> <input type="text" name="title" size="64" required="" id="id_title"></p>
<p><label for="id_tags">Tags:</label> <input  autocomplete="off" type="text" name="tags" size="64" id="id_tags" ></p>
    <input type="submit" value="save">
    
    </form>

bookmarks/templates/bookmarks/friend_invite.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans 'Invite A Friend' %}{% endblock %}
{% block head %}{% trans 'Invite A Friend' %}{% endblock %}
{% block content %}
Enter your friend name and email below, and click "send invite" to invite your friend to join the site  
<form method="post" action=".">
    {% csrf_token %}
{{ form.as_p }}
<input type="submit" value="{% trans 'send invite' %}" />
</form>
{% endblock %}

bookmarks/templates/bookmarks/friends_page.html
{% extends "base.html" %}
{% block title %}Friends for {{ username }}{% endblock %}
{% block head %}Friends for {{ username }}{% endblock %}
{% block content %}
<h2>Friend List</h2>
{% if friends %}
<ul class="friends">
{% for friend in friends %}
<li><a href="/user/{{ friend.username }}/">
{{ friend.username }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>No friends found.</p>
{% endif %}
<a href="/friend/invite/">Invite a friend!</a>
<h2>Latest Friend Bookmarks</h2>
{% include 'bookmark_list.html' %}
{% endblock %}

bookmarks/templates/bookmarks/main_page.html
{% extends "base.html" %}

{% block title %}Welcome to Django Bookmarks{% endblock %}
{% block head %}Welcome to Django Bookmarks{% endblock %}
{% block external %}
<link rel="alternate" type="application/rss+xml"
title="Django Bookmarks | Recent Bookmarks"
href="/feeds/recent/" />
{% endblock %}
{% block content %}
{% if user.username %}
<p>Welcome {{ user.username }}!
Here you can store and share bookmarks!</p>
{% else %}
<p>Welcome anonymous user!
You need to <a href="/login/">login</a>
before you can store and share bookmarks.</p>
{% endif %}
<h2>Bookmarks Shared by Users</h2>
{% include 'shared_bookmark_list.html' %}
{% endblock %}

bookmarks/templates/bookmarks/popular_page.html
{% extends "base.html" %}
{% block title %}Popular Bookmarks{% endblock %}
{% block head %}Popular Bookmarks{% endblock %}
{% block content %}
{% include 'shared_bookmark_list.html' %}
{% endblock %}

bookmarks/templates/bookmarks/search.html
{% extends "base.html" %}
{% load static %}
{% block external %}
<script type="text/javascript" src="{% static 'js/search.js' %}">
</script>
{% endblock %}
{% block title %}Search Bookmarks{% endblock %}
{% block head %}Search Bookmarks{% endblock %}
{% block content %}
<form id="search-form" method="get" action=".">
{{ form.as_p }}
<input type="submit" value="search" />
</form>
<div id="search-results">
{% if show_results %}
{% include 'bookmark_list.html' %}
{% endif %}
</div>
{% endblock %}

bookmarks/templates/bookmarks/shared_bookmark_list.html
{% if shared_bookmarks %}
<ul class="bookmarks">
{% for shared_bookmark in shared_bookmarks %}
<li>
    <a href="/vote/?id={{ shared_bookmark.id }}"
class="vote">[+]</a>
<a href="{{ shared_bookmark.bookmark.link.url }}"
class="title">
{{ shared_bookmark.bookmark.title|escape }}</a>
<br />
Posted By:
<a href="/user/{{ shared_bookmark.bookmark.user.username }}/"
class="username">
{{ shared_bookmark.bookmark.user.username }}</a> |
<span class="vote-count">Votes:
    {{ shared_bookmark.votes }}</span> |
    <a href="/bookmark/{{ shared_bookmark.id}}/">Comments</a>
</li>
{% endfor %}
</ul>
{% else %}
<p>No bookmarks found.</p>
{% endif %}

bookmarks/templates/bookmarks/tag_cloud_page.html
{% extends "base.html" %}
{% block title %}Tag Cloud{% endblock %}
{% block head %}Tag Cloud{% endblock %}
{% block content %}
<div id="tag-cloud">
{% for tag in tags %}
<a href="/tag/{{ tag.name|urlencode }}/"
class="tag-cloud-{{ forloop.counter }}">
{{ tag.name|escape }}</a>
{% endfor %}
</div>
{% endblock %}

bookmarks/templates/bookmarks/tag_page.html
{% extends "base.html" %}
{% block title %}Tag: {{ tag_name|escape }}{% endblock %}
{% block head %}
Bookmarks for tag: {{ tag_name|escape }}
{% endblock%}
{% block content %}
{% include "bookmark_list.html" %}
{% endblock %}

bookmarks/templates/bookmarks/user_page.html
{% extends "base.html" %}
{% load static %}
{% block external %}
<script type="text/javascript" src="{% static 'js/bookmark_edit.js' %}">
</script>
{% endblock %}
{% block title %}{{ username }}{% endblock %}
{% block head %}Bookmarks for {{ username }}{% endblock %}
{% block content %}
{% ifequal user.username username %}
<a href="/friends/{{ username }}/">view your friends</a>
{% else %}
{% if is_friend %}
<a href="/friends/{{ user.username }}/">
{{ username }} is a friend of yours</a>
{% else %}
<a href="/friend/add/?username={{ username }}">
add {{ username }} to your friends</a>
{% endif %}
- <a href="/friends/{{ username }}/">
view {{username }}'s friends</a>
{% endifequal %}
{% include "bookmark_list.html" %}
{% endblock %}